version: '3.9'
services:
  # Frontend Service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: jasminegraph-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - BACKEND=http://backend:8080 # Pointing to the backend service
      - NEXT_PUBLIC_API_URL=http://backend:8080 # Pointing to the backend service
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Backend Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: jasminegraph-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      mongoCont:
        condition: service_healthy
    volumes:
      - /var/tmp/jasminegraph-ui-backend:/app/caches
    environment:
      - MONGO_URL=mongodb://mongoCont:27017/jasminegraph  
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 15s

  # MongoDB Service
  mongoCont:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Playwright Test Service
  playwright:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    environment:
      - BASE_URL=http://frontend:3000   

volumes:
  mongodb-data:
    driver: local
