name: Playwright Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Playwright tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: Frontend
        run: npm install

      - name: Install Playwright Browsers
        working-directory: Frontend
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: Frontend
        run: npx playwright test
